# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

def fib_sequence
  Enumerator.new do |enum|
    previous = [0, 1]
    while true
      val = previous.reduce(:+)
      enum.yield(val)
      previous << val
      previous.shift
    end
  end
end

fibs = fib_sequence.take_while{|n| n < 4_000_000}
sum  = fibs.select{|n| n % 2 == 0}.reduce(:+)
puts sum
